stages:
- stage: Docker
  displayName: Build & Push Docker image to AWS ECR
  jobs:
  - job: Build_and_Push
    displayName: Build & Push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        repository: $(my-docker-repo)

    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'ecr_connection'
        regionName: $(us-east-2)
        imageSource: 'latest'
        sourceImageName: $(my-docker-repo)
        sourceImageTag: $(Build.BuildId)
        pushTag: latest
        repositoryName: $(my-docker-repo)
